### ISSUE TITLE
Windows phone 8.1  - App crashes after using FlashLight

### ISSUE THREAD

**Issue by artev** [EddyVerbruggen/Flashlight-PhoneGap-Plugin#20]
Hi there,
I'm developing a cordova app that uses your Flashlight plugin.
Everything works great on android and ios, but my app crashes on WP8 (Windows phone 8.1 ) 

Here is the sequence  : 

- I switch on the flashlight using  window.plugins.flashlight.switchOn(); ( It works, the light is on )
- Then I click on a link in my cordova app (ex: http://www.google.com ) . 
 that pauses my app and opens the system's web browser ( i'm using cordova-plugin-inappbrowser )
- Then I click on the Back button, it opens back my app and resumes it
- If I try to switch on the flashlight again, i get a nasty "System.ObjectDisposedException"
it says  "The object has been closed. Fatal error. Disposing capture device"

Here is the detail of the StackTrace : 
```
    at Windows.Phone.Media.Capture.AudioVideoCaptureDevice.SetProperty(Guid propertyId, Object value)
   at WPCordovaClassLib.Cordova.Commands.Flashlight.<switchOff>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()}	System.Exception {System.ObjectDisposedException}
```
![error](https://cloud.githubusercontent.com/assets/9623848/7023570/8095e06e-dd36-11e4-8855-9ce6b2e8ab92.jpg)

![error-2](https://cloud.githubusercontent.com/assets/9623848/7023574/884956e2-dd36-11e4-9c5b-adb34ac0338d.jpg)

Thanks for your help

**Comment by EddyVerbruggen** [comment]
Hi @artev thanks for the bugreport!

Can you please give v 2.0.3 a try? I think it fixes your trouble.

Best,
Eddy

**Comment by artev** [comment]
Hi @EddyVerbruggen ! 
updating to v 2.0.3 solved my problem
Thanks very much !

**Comment by EddyVerbruggen** [comment]
Wonderful! Thanks for testing the fix,
Eddy
